---
- hosts: all
  tasks:
    - name: 'Install operational system packages dependencies'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
    - name: 'Install PHP5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Install Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: 'Install modphp'
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes